FROM node:18

RUN apt-get update && \
  apt-get install -y vim less python3 python3-pip build-essential && \
  ln -s /usr/bin/python3 /usr/bin/python

RUN npm install -g pnpm nodemon @adonisjs/cli

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./

RUN pnpm install --frozen-lockfile

COPY . .

CMD ["pnpm", "run", "dev"]
