version: '3.1'
services:
  client:
    build:
      context: ./
      dockerfile: ./Dockerfile_client
    command: bash -c "npm install  && yarn build"
    working_dir: /app
    tty: true
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
        # ports:
        # - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules

  websocket:
    build:
      context: ./
      dockerfile: ./Dockerfile_websocket
    command: bash -c 'npm install && npm run dev'
    working_dir: /app
    restart: always
    ports:
      - 3030:3030
    volumes:
      - ./websocket:/app
      - /app/node_modules
  nginx:
    image: nginx
    restart: always
    ports:
            - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./client/build:/var/www
