services:
  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile_client
    command: pnpm run build
    working_dir: /app
    tty: true
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
      - pnpm_store:/root/.local/share/pnpm/store

  websocket:
    build:
      context: ./websocket
      dockerfile: ../Dockerfile_websocket
    command: pnpm run dev
    working_dir: /app
    restart: always
    ports:
      - 3030:3030
    volumes:
      - ./websocket:/app
      - websocket_node_modules:/app/node_modules
      - pnpm_store:/root/.local/share/pnpm/store
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./client/build:/var/www

volumes:
  client_node_modules:
  websocket_node_modules:
  pnpm_store:
